version: "3"
services: 
  consultaassesso:
    build: ./
    environment: 
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/ConAsse
    ports:
      - 3002:8080
    links:
      - db
    depends_on: 
      - db
  db:
    image: mongo:latest
    expose:
    - 27017
    ports:
      - 27017:27017
#    command: --smallfiles
  #  environment:
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_USER=api
  #    - POSTGRES_DB=postgres
    restart: unless-stopped